### ISSUE TITLE
java.lang.NoSuchMethodError: org.apache.maven.plugin.MojoFailureException: method 'void <init>(java.lang.Throwable)' not found

### ISSUE THREAD

**Issue by cezar-tech** [spotify/fmt-maven-plugin#181]
**Describe the bug**

Hello, the format just stops working,  I haven't changed my java nor maven version recently.

The full debug trace for a maven command:

```
[ERROR] Failed to execute goal com.spotify.fmt:fmt-maven-plugin:2.21.1:format (default-cli) on project REDACTED: Execution default-cli of goal com.spotify.fmt:fmt-maven-plugin:2.21.1:format failed: An API incompatibility was encountered while executing com.spotify.fmt:fmt-maven-plugin:2.21.1:format: java.lang.NoSuchMethodError: org.apache.maven.plugin.MojoFailureException: method 'void <init>(java.lang.Throwable)' not found
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>com.spotify.fmt:fmt-maven-plugin:2.21.1
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/home/cezar/.m2/repository/com/spotify/fmt/fmt-maven-plugin/2.21.1/fmt-maven-plugin-2.21.1.jar
[ERROR] urls[1] = file:/home/cezar/.m2/repository/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
[ERROR] urls[2] = file:/home/cezar/.m2/repository/javax/annotation/javax.annotation-api/1.2/javax.annotation-api-1.2.jar
[ERROR] urls[3] = file:/home/cezar/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.5/org.eclipse.sisu.inject-0.3.5.jar
[ERROR] urls[4] = file:/home/cezar/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
[ERROR] urls[5] = file:/home/cezar/.m2/repository/org/codehaus/plexus/plexus-utils/3.5.1/plexus-utils-3.5.1.jar
[ERROR] urls[6] = file:/home/cezar/.m2/repository/com/google/googlejavaformat/google-java-format/1.17.0/google-java-format-1.17.0.jar
[ERROR] urls[7] = file:/home/cezar/.m2/repository/com/google/guava/guava/32.1.2-jre/guava-32.1.2-jre.jar
[ERROR] urls[8] = file:/home/cezar/.m2/repository/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
[ERROR] urls[9] = file:/home/cezar/.m2/repository/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar
[ERROR] urls[10] = file:/home/cezar/.m2/repository/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar
[ERROR] urls[11] = file:/home/cezar/.m2/repository/org/checkerframework/checker-qual/3.33.0/checker-qual-3.33.0.jar
[ERROR] urls[12] = file:/home/cezar/.m2/repository/com/google/errorprone/error_prone_annotations/2.18.0/error_prone_annotations-2.18.0.jar
[ERROR] urls[13] = file:/home/cezar/.m2/repository/com/google/j2objc/j2objc-annotations/2.8/j2objc-annotations-2.8.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR] 
[ERROR] -----------------------------------------------------
[ERROR] 
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.spotify.fmt:fmt-maven-plugin:2.21.1:format (default-cli) on project linkedin-collector: Execution default-cli of goal com.spotify.fmt:fmt-maven-plugin:2.21.1:format failed: An API incompatibility was encountered while executing com.spotify.fmt:fmt-maven-plugin:2.21.1:format: java.lang.NoSuchMethodError: org.apache.maven.plugin.MojoFailureException: method 'void <init>(java.lang.Throwable)' not found
-----------------------------------------------------
realm =    plugin>com.spotify.fmt:fmt-maven-plugin:2.21.1
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
urls[0] = file:/home/cezar/.m2/repository/com/spotify/fmt/fmt-maven-plugin/2.21.1/fmt-maven-plugin-2.21.1.jar
urls[1] = file:/home/cezar/.m2/repository/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
urls[2] = file:/home/cezar/.m2/repository/javax/annotation/javax.annotation-api/1.2/javax.annotation-api-1.2.jar
urls[3] = file:/home/cezar/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.5/org.eclipse.sisu.inject-0.3.5.jar
urls[4] = file:/home/cezar/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
urls[5] = file:/home/cezar/.m2/repository/org/codehaus/plexus/plexus-utils/3.5.1/plexus-utils-3.5.1.jar
urls[6] = file:/home/cezar/.m2/repository/com/google/googlejavaformat/google-java-format/1.17.0/google-java-format-1.17.0.jar
urls[7] = file:/home/cezar/.m2/repository/com/google/guava/guava/32.1.2-jre/guava-32.1.2-jre.jar
urls[8] = file:/home/cezar/.m2/repository/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
urls[9] = file:/home/cezar/.m2/repository/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar
urls[10] = file:/home/cezar/.m2/repository/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar
urls[11] = file:/home/cezar/.m2/repository/org/checkerframework/checker-qual/3.33.0/checker-qual-3.33.0.jar
urls[12] = file:/home/cezar/.m2/repository/com/google/errorprone/error_prone_annotations/2.18.0/error_prone_annotations-2.18.0.jar
urls[13] = file:/home/cezar/.m2/repository/com/google/j2objc/j2objc-annotations/2.8/j2objc-annotations-2.8.jar
Number of foreign imports: 1
import: Entry[import  from realm ClassRealm[maven.api, parent: null]]

-----------------------------------------------------

    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:564)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal com.spotify.fmt:fmt-maven-plugin:2.21.1:format failed: An API incompatibility was encountered while executing com.spotify.fmt:fmt-maven-plugin:2.21.1:format: java.lang.NoSuchMethodError: org.apache.maven.plugin.MojoFailureException: method 'void <init>(java.lang.Throwable)' not found
-----------------------------------------------------
realm =    plugin>com.spotify.fmt:fmt-maven-plugin:2.21.1
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
urls[0] = file:/home/cezar/.m2/repository/com/spotify/fmt/fmt-maven-plugin/2.21.1/fmt-maven-plugin-2.21.1.jar
urls[1] = file:/home/cezar/.m2/repository/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
urls[2] = file:/home/cezar/.m2/repository/javax/annotation/javax.annotation-api/1.2/javax.annotation-api-1.2.jar
urls[3] = file:/home/cezar/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.5/org.eclipse.sisu.inject-0.3.5.jar
urls[4] = file:/home/cezar/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
urls[5] = file:/home/cezar/.m2/repository/org/codehaus/plexus/plexus-utils/3.5.1/plexus-utils-3.5.1.jar
urls[6] = file:/home/cezar/.m2/repository/com/google/googlejavaformat/google-java-format/1.17.0/google-java-format-1.17.0.jar
urls[7] = file:/home/cezar/.m2/repository/com/google/guava/guava/32.1.2-jre/guava-32.1.2-jre.jar
urls[8] = file:/home/cezar/.m2/repository/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
urls[9] = file:/home/cezar/.m2/repository/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar
urls[10] = file:/home/cezar/.m2/repository/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar
urls[11] = file:/home/cezar/.m2/repository/org/checkerframework/checker-qual/3.33.0/checker-qual-3.33.0.jar
urls[12] = file:/home/cezar/.m2/repository/com/google/errorprone/error_prone_annotations/2.18.0/error_prone_annotations-2.18.0.jar
urls[13] = file:/home/cezar/.m2/repository/com/google/j2objc/j2objc-annotations/2.8/j2objc-annotations-2.8.jar
Number of foreign imports: 1
import: Entry[import  from realm ClassRealm[maven.api, parent: null]]

-----------------------------------------------------

    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:186)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:564)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.apache.maven.plugin.PluginContainerException: An API incompatibility was encountered while executing com.spotify.fmt:fmt-maven-plugin:2.21.1:format: java.lang.NoSuchMethodError: org.apache.maven.plugin.MojoFailureException: method 'void <init>(java.lang.Throwable)' not found
-----------------------------------------------------
realm =    plugin>com.spotify.fmt:fmt-maven-plugin:2.21.1
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
urls[0] = file:/home/cezar/.m2/repository/com/spotify/fmt/fmt-maven-plugin/2.21.1/fmt-maven-plugin-2.21.1.jar
urls[1] = file:/home/cezar/.m2/repository/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
urls[2] = file:/home/cezar/.m2/repository/javax/annotation/javax.annotation-api/1.2/javax.annotation-api-1.2.jar
urls[3] = file:/home/cezar/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.5/org.eclipse.sisu.inject-0.3.5.jar
urls[4] = file:/home/cezar/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
urls[5] = file:/home/cezar/.m2/repository/org/codehaus/plexus/plexus-utils/3.5.1/plexus-utils-3.5.1.jar
urls[6] = file:/home/cezar/.m2/repository/com/google/googlejavaformat/google-java-format/1.17.0/google-java-format-1.17.0.jar
urls[7] = file:/home/cezar/.m2/repository/com/google/guava/guava/32.1.2-jre/guava-32.1.2-jre.jar
urls[8] = file:/home/cezar/.m2/repository/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
urls[9] = file:/home/cezar/.m2/repository/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar
urls[10] = file:/home/cezar/.m2/repository/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar
urls[11] = file:/home/cezar/.m2/repository/org/checkerframework/checker-qual/3.33.0/checker-qual-3.33.0.jar
urls[12] = file:/home/cezar/.m2/repository/com/google/errorprone/error_prone_annotations/2.18.0/error_prone_annotations-2.18.0.jar
urls[13] = file:/home/cezar/.m2/repository/com/google/j2objc/j2objc-annotations/2.8/j2objc-annotations-2.8.jar
Number of foreign imports: 1
import: Entry[import  from realm ClassRealm[maven.api, parent: null]]

-----------------------------------------------------

    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:184)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:564)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: java.lang.NoSuchMethodError: org.apache.maven.plugin.MojoFailureException: method 'void <init>(java.lang.Throwable)' not found
    at com.spotify.fmt.AbstractFMT.execute (AbstractFMT.java:178)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:564)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
```

My java and mvn versions:
```
Apache Maven 3.6.3
Maven home: /usr/share/maven
Java version: 14.0.2, vendor: AdoptOpenJDK, runtime: /home/cezar/.sdkman/candidates/java/14.0.2.hs-adpt
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "6.2.0-33-generic", arch: "amd64", family: "unix"

openjdk version "14.0.2" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 14.0.2+12)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 14.0.2+12, mixed mode, sharing)
```

**To Reproduce**
Steps to reproduce the behavior.
```
mvn com.spotify.fmt:fmt-maven-plugin:format -e -X
```

**Expected behavior**
Should format the code normally.

**Additional context**
I am on linux, but this problem seems to be widespread in my company, many people here report the same error, they should have machines configured like mine.

**Comment by cezar-tech** [comment]
As additional info, it does run for some maven modules of ours, but fails on some.

In my case it fails in a particular file, out of nowhere:

```
[error] Failed to format file 'REDACTED.java'.

com.google.googlejavaformat.java.FormatterException: 450:13: error: expected token: '-'; generated : instead
	at com.google.googlejavaformat.java.Formatter.getFormatReplacements(Formatter.java:275)
	at com.google.googlejavaformat.java.Formatter.formatSource(Formatter.java:247)
	at com.google.googlejavaformat.java.Formatter.formatSource(Formatter.java:213)
	at com.spotify.fmt.Formatter.formatSourceFile(Formatter.java:156)
	at com.spotify.fmt.Formatter.lambda$formatSourceFilesInDirectory$1(Formatter.java:93)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:952)
	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:926)
	at java.base/java.util.stream.AbstractTask.compute(AbstractTask.java:327)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by caesar-ralf** [comment]
Hey @cezar-tech.

I have tested the plugin with different JDK versions (11, 17 & 21) and different projects locally and I was not able to replicate your issue. Would you be able to create a sample project with the problem happening so that we can try to see where the problem lies?

**Comment by cezar-tech** [comment]
Hi @caesar-ralf , 

I have created this repo:
https://github.com/cezar-tech/test-java-format

It seems that the main problem is this error I mentioned: https://github.com/spotify/fmt-maven-plugin/issues/181#issuecomment-1749556082

I was somehow replicated in this repo I created. It appears to be a problema related to the switch case expression different versions that released in java.

Even though in my example repo the error is:
```
mvn com.spotify.fmt:fmt-maven-plugin:format
[WARNING] 
[WARNING] Some problems were encountered while building the effective settings
[WARNING] Unrecognised tag: 'blocked' (position: START_TAG seen ...</url>\n      <blocked>... @164:16)  @ /usr/share/maven/conf/settings.xml, line 164, column 16
[WARNING] 
[INFO] Scanning for projects...
[INFO] 
[INFO] -------------------< br.com.cezar:test-java-format >--------------------
[INFO] Building test-java-format 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- fmt-maven-plugin:2.21.1:format (default-cli) @ test-java-format ---
[WARNING] Test source directory '/home/cezar/IdeaProjects/test-java-format/src/test/java' does not exist, ignoring.
[error] Failed to format file '/home/cezar/IdeaProjects/test-java-format/src/main/java/main/Main.java'.

com.google.googlejavaformat.java.FormatterException: 9:6: error: expected token: 'switch'; generated ( instead
	at com.google.googlejavaformat.java.Formatter.getFormatReplacements(Formatter.java:275)
	at com.google.googlejavaformat.java.Formatter.formatSource(Formatter.java:247)
	at com.google.googlejavaformat.java.Formatter.formatSource(Formatter.java:213)
	at com.spotify.fmt.Formatter.formatSourceFile(Formatter.java:156)
	at com.spotify.fmt.Formatter.lambda$formatSourceFilesInDirectory$1(Formatter.java:93)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:952)
	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:926)
	at java.base/java.util.stream.AbstractTask.compute(AbstractTask.java:327)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.089 s
[INFO] Finished at: 2023-10-06T11:09:25-03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.spotify.fmt:fmt-maven-plugin:2.21.1:format (default-cli) on project test-java-format: Execution default-cli of goal com.spotify.fmt:fmt-maven-plugin:2.21.1:format failed: An API incompatibility was encountered while executing com.spotify.fmt:fmt-maven-plugin:2.21.1:format: java.lang.NoSuchMethodError: org.apache.maven.plugin.MojoFailureException: method 'void <init>(java.lang.Throwable)' not found
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>com.spotify.fmt:fmt-maven-plugin:2.21.1
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/home/cezar/.m2/repository/com/spotify/fmt/fmt-maven-plugin/2.21.1/fmt-maven-plugin-2.21.1.jar
[ERROR] urls[1] = file:/home/cezar/.m2/repository/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
[ERROR] urls[2] = file:/home/cezar/.m2/repository/javax/annotation/javax.annotation-api/1.2/javax.annotation-api-1.2.jar
[ERROR] urls[3] = file:/home/cezar/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.5/org.eclipse.sisu.inject-0.3.5.jar
[ERROR] urls[4] = file:/home/cezar/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
[ERROR] urls[5] = file:/home/cezar/.m2/repository/org/codehaus/plexus/plexus-utils/3.5.1/plexus-utils-3.5.1.jar
[ERROR] urls[6] = file:/home/cezar/.m2/repository/com/google/googlejavaformat/google-java-format/1.17.0/google-java-format-1.17.0.jar
[ERROR] urls[7] = file:/home/cezar/.m2/repository/com/google/guava/guava/32.1.2-jre/guava-32.1.2-jre.jar
[ERROR] urls[8] = file:/home/cezar/.m2/repository/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
[ERROR] urls[9] = file:/home/cezar/.m2/repository/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar
[ERROR] urls[10] = file:/home/cezar/.m2/repository/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar
[ERROR] urls[11] = file:/home/cezar/.m2/repository/org/checkerframework/checker-qual/3.33.0/checker-qual-3.33.0.jar
[ERROR] urls[12] = file:/home/cezar/.m2/repository/com/google/errorprone/error_prone_annotations/2.18.0/error_prone_annotations-2.18.0.jar
[ERROR] urls[13] = file:/home/cezar/.m2/repository/com/google/j2objc/j2objc-annotations/2.8/j2objc-annotations-2.8.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR] 
[ERROR] -----------------------------------------------------
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException
```


It ends up that in my original repo after rolling back all switch statements to the old style ones the format worked.

**Comment by cezar-tech** [comment]
Basically this switch doesnt work:

```
        switch ("a") {
          case "videos" -> null;
          case "images" -> null;
          default -> null;
        };
```
but this one does:
```
    switch ("a") {
      case "videos":
        apiResponse = null;
        break;
      case "images":
        apiResponse = null;
        break;
      default:
        apiResponse = null;
        break;
    }
```

**Comment by caesar-ralf** [comment]
So I tested your project locally @cezar-tech and I managed to run the formatter as expected:

![image](https://github.com/spotify/fmt-maven-plugin/assets/1277484/113e489b-da03-4c34-a71d-5c607f0ce9f9)

I am using java 17 corretto distribution:

```
openjdk 17.0.8 2023-07-18 LTS
OpenJDK Runtime Environment Corretto-17.0.8.7.1 (build 17.0.8+7-LTS)
OpenJDK 64-Bit Server VM Corretto-17.0.8.7.1 (build 17.0.8+7-LTS, mixed mode, sharing)
```

I tried with the adoptopenjdk one which is now called Temurin, and I got the same result

![image](https://github.com/spotify/fmt-maven-plugin/assets/1277484/5e1b68eb-66ea-4214-b827-57031e9b7e38)

I haven't found the JDK 14 to install to test it locally, but could you try it out @cezar-tech?

**Comment by cezar-tech** [comment]
@caesar-ralf 

It does indeed work with java 17....
![image](https://github.com/spotify/fmt-maven-plugin/assets/56096912/c38a84db-89bf-455a-a3e9-e3da6536a352)



Maybe a plague for not using the an LTS version ? :(. Probably not worth fixing either right ?
Should be better that we start using LTS versions only.
![image](https://github.com/spotify/fmt-maven-plugin/assets/56096912/4f8691f7-99fc-4960-ad83-cbba447f21b8)

**Comment by cezar-tech** [comment]
Our ci already uses java 17 so it only fails locally in our pc where we have java 14 installed.

We cant change the maven compiler java version yet, I think that would be ok to install java 17 only for formatting purposes in my company.

**Comment by caesar-ralf** [comment]
> Our ci already uses java 17 so it only fails locally in our pc where we have java 14 installed.
> 
> We cant change the maven compiler java version yet, I think that would be ok to install java 17 only for formatting purposes in my company.

yeah, sorry, we only support the LTS versions as it's not the simplest to support the other versions. The issue seems to be in the google format library itself as well and not in our plugin. Maybe they can help out?

**Comment by cezar-tech** [comment]
ok @caesar-ralf  thank you for your time. I have recommended ppl to install java 17 in their OS's and this will temporarily fix the problem. And I think our main goal should be upgrading to LTS versions.
